# Generated by Django 3.0 on 2019-12-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191220_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ManyToManyField(to='main.Categoria'),
        ),
    ]
